routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',"Site\HomeController@index")->name('home.index');
Route::get('/market',"Site\HomeController@market")->name('home.market');
Route::get('/about-us',"Site\HomeController@aboutUs")->name('home.aboutus');
Route::get('/pricing',"Site\HomeController@pricing")->name('home.pricing');
Route::get('/faq',"Site\HomeController@faq")->name('home.faq');
Route::get('/terms-of-service',"Site\HomeController@termsandservices")->name('home.termsandservices');
Route::get('/privacy-policy',"Site\HomeController@privacypolicy")->name('home.privacypolicy');
Route::get('/profile',"Site\HomeController@profile")->name('home.profile');
Route::get('/anti-money-laundering',"Site\HomeController@antimoney")->name('home.antimoney');
Route::get('/login',"Site\HomeController@login")->name('home.login');
Route::get('/signup',"Site\HomeController@signup")->name('home.signup');
Route::get('/contact-us',"Site\HomeController@contact")->name('home.contact');
Route::post('AjaxCallForContactUsSubmitAndEmail',"Site\HomeController@AjaxCallForContactUsSubmitAndEmail")->name('AjaxCallForContactUsSubmitAndEmail');

Route::post('/AjaxCallForSaveThemeInCookie',"Site\HomeController@AjaxCallForSaveThemeInCookie")->name('AjaxCallForSaveThemeInCookie');
Route::get('/AjaxCallForGetThemeInCookie',"Site\HomeController@AjaxCallForGetThemeInCookie")->name('AjaxCallForGetThemeInCookie');




// =========== Admin Auth Routes ==============//
Route::prefix('admin')->group(function () {

    // =========== Admin Login Routes ==============//
    Route::middleware('guest:admin')->group(function () {
        Route::get('/login',"Admin\AuthController@loginShow")->name('admin.login');
        Route::post('/login',"Admin\AuthController@loginPost")->name('admin.login.store');

        Route::get('/forgotPassword',"Admin\AuthController@EmailResetPasswordPage")->name('forgotPassword.email'); // Forgot Password send email 

        Route::post('/AjaxCallForForgotPasswordEmail',"Admin\AuthController@AjaxCallForForgotPasswordEmail")->name('AjaxCallForForgotPasswordEmail'); // Forgot Password send email 

        Route::get('/resetPassword/{email_encode}',"Admin\AuthController@ResetPassword")->name('resetPassword'); // Forgot Password send email 

        Route::post('/SetNewPassword',"Admin\AuthController@SetNewPassword")->name('SetNewPassword'); // Set New Password 


    });
    // =========== Admin Authenticate Routes ==============//
    Route::middleware('auth:admin')->group(function () {
        
        Route::get('home',"Admin\HomeController@index")->name('home');
        Route::get('/logout',"Admin\AuthController@logout")->name('admin.logout');
        // =========== Admin CMS Routes ==============//
        Route::resource('news',"Admin\CMS\NewsController");
        Route::resource('widget',"Admin\CMS\WidgetController");
        // Route::resource('about-us',"Admin\CMS\AboutUsController");

        Route::post('about-us/store',"Admin\CMS\CMSController@AboutUsCreateOrUpdate")->name('about-us.store');

        Route::get('about-us/create',"Admin\CMS\CMSController@AboutUs")->name('about-us.create');


        Route::post('home/store',"Admin\CMS\CMSController@HomeCreateOrUpdate")->name('home.store');

        Route::get('home/create',"Admin\CMS\CMSController@Home")->name('home.create');

        Route::get('pricing/create',"Admin\CMS\CMSController@Pricing")->name('pricing.create');
        //Faq
        Route::group(['prefix' => 'faq'], function () {
            Route::get('add/{id?}', 'Admin\CMS\FaqController@add')->name('faq.add');
            Route::post('post', 'Admin\CMS\FaqController@post')->name('faq.post');
            Route::get('/', 'Admin\CMS\FaqController@index')->name('faq.view');
            Route::get('/delete/{id}', 'Admin\CMS\FaqController@delete')->name('faq.delete');
            Route::post('AjaxCallForSaveFaqMetaData','Admin\CMS\CMSController@AjaxCallForSaveFaqMetaData')->name('AjaxCallForSaveFaqMetaData');

        });

        Route::post('pricing/store',"Admin\CMS\CMSController@PricingCreateOrUpdate")->name('pricing.store');

        Route::get('antiMoneyLaundring/create',"Admin\CMS\CMSController@AntiMoneyLaundring")->name('antiMoneyLaundring.create');
        Route::post('antiMoneyLaundring/store',"Admin\CMS\CMSController@AntiMoneyLaundringCreateOrUpdate")->name('antiMoneyLaundring.store');

        Route::get('privacyPolicy/create',"Admin\CMS\CMSController@PrivacyPolicy")->name('privacyPolicy.create');
        Route::post('privacyPolicy/store',"Admin\CMS\CMSController@PrivacyPolicyCreateOrUpdate")->name('privacyPolicy.store');

        
        Route::get('termsAndServices/create',"Admin\CMS\CMSController@TermsAndServices")->name('termsAndServices.create');
        Route::post('termsAndServices/store',"Admin\CMS\CMSController@TermsAndServicesCreateOrUpdate")->name('termsAndServices.store');

        Route::get('setting','Admin\SettitngController@index')->name('setting');
        Route::post('ChangePassword','Admin\SettitngController@ChangePassword')->name('ChangePassword');

        Route::get('contactUs',"Admin\CMS\CMSController@ContactUs")->name('contactUs.index');
        Route::post('AjaxCallForViewContactUs',"Admin\CMS\CMSController@AjaxCallForViewContactUs")->name('AjaxCallForViewContactUs');
        
        Route::post('ContactUsDelete',"Admin\CMS\CMSController@ContactUsDelete")->name('ContactU.delete');

        Route::post('AjaxCallForSaveContactUsMetaData','Admin\CMS\CMSController@AjaxCallForSaveContactUsMetaData')->name('AjaxCallForSaveContactUsMetaData');
        
    });
});

resources/views/admin/partials/aside.blade.php
 
 <!-- Main Sidebar Container -->
 <aside class="main-sidebar sidebar-dark-primary elevation-4">
     <!-- Brand Logo -->
     <a href="#" class="brand-link">
         {{-- <img src="{{asset('backend/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3" style="opacity: .8"> --}}
             <img src="{{asset('frontend/img/logo.png')}}" alt="V-Trader Logo"
             class="" style="opacity: .8;width:50px">
         <span class="brand-text font-weight-light">V-Trader</span>
     </a>

     <!-- Sidebar -->
     <div class="sidebar">
         <!-- Sidebar user panel (optional) -->
         <div class="user-panel mt-3 pb-3 mb-3 d-flex">
             <div class="image">
                 {{-- <img src="{{asset('backend/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2"
                     alt="User Image"> --}}
                     <div  id="profileImage" class="img-circle"></div>
             </div>
             <div class="info">
                 <a href="#" class="d-block">{{Auth::user()->name}}</a>
                 <small><i class="fas fa-cog" style="color: #c2c7d0;"></i> <a href="{{route('setting')}}">Settings</a></small>
             </div>
         </div>

         <!-- SidebarSearch Form -->
         {{-- <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div> --}}

         <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                 data-accordion="false">
                 <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
			   	<li class="nav-item">
					<a href="{{route('home')}}" class="nav-link">
						<i class="nav-icon fas fa-chart-pie"></i>
						<p>
							Dashboard
							{{-- <i class="right fas fa-angle-left"></i> --}}
						</p>
					</a>
			   	</li>
                   <li class="nav-item">
                    <a href="{{route('widget.index')}}" class="nav-link {{ ( Route::currentRouteName() == 'widget.index' || Route::currentRouteName() == 'widget.create' || Route::currentRouteName() == 'widget.edit') ? 'active' : '' }}">
                        <i class="nav-icon fas fa-chart-pie"></i>
                        <p>Widget</p>
                    </a>
                </li>
                   {{-- {{ ( Route::currentRouteName() == 'faq.view' || Route::currentRouteName() == 'faq.add') ? 'menu-is-opening menu-open' : '' }} --}}
                   @php
                        $arr = array("termsAndServices.create", "privacyPolicy.create", "antiMoneyLaundring.create", "home.create", "about-us.create", "faq.view", "faq.add", "pricing.create", "news.edit", "news.create", "news.index","contactUs.index","widget.edit", "widget.create", "widget.index");
                   @endphp
				<li class="nav-item {{ in_array(Route::currentRouteName(),$arr)? 'menu-is-opening menu-open' : '' }}" id="CMS_dropDown">
					<a href="#" class="nav-link" data-value="CMS">
						<i class="nav-icon fas fa-chart-pie"></i>
						<p>
							CMS
							<i class="right fas fa-angle-left"></i>
						</p>
					</a>
					<ul class="nav nav-treeview">
						<li class="nav-item">
							<a href="{{route('home.create')}}" class="nav-link {{ ( Route::currentRouteName() == 'home.create' ) ? 'active' : '' }}" ">
								<i class="far fa-circle nav-icon"></i>
								<p>Home</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{route('about-us.create')}}" class="nav-link {{ ( Route::currentRouteName() == 'about-us.create' ) ? 'active' : '' }}" ">
								<i class="far fa-circle nav-icon"></i>
								<p>About Us</p>
							</a>
						</li>

						<li class="nav-item">
							<a href="{{route('news.index')}}" class="nav-link {{ ( Route::currentRouteName() == 'news.index' || Route::currentRouteName() == 'news.create' || Route::currentRouteName() == 'news.edit') ? 'active' : '' }}">
								<i class="far fa-circle nav-icon"></i>
								<p>News</p>
							</a>
						</li>

                        <li class="nav-item">
							<a href="{{route('faq.view')}}" class="nav-link {{ ( Route::currentRouteName() == 'faq.view' || Route::currentRouteName() == 'faq.add') ? 'active' : '' }}" ">
								<i class="far fa-circle nav-icon"></i>
								<p>Faq</p>
							</a>
						</li>

                        <li class="nav-item">
							<a href="{{route('pricing.create')}}" class="nav-link {{ ( Route::currentRouteName() == 'pricing.create' ) ? 'active' : '' }}">
								<i class="far fa-circle nav-icon"></i>
								<p>Pricing</p>
							</a>
						</li>

                        <li class="nav-item">
							<a href="{{route('antiMoneyLaundring.create')}}" class="nav-link {{ ( Route::currentRouteName() == 'antiMoneyLaundring.create' ) ? 'active' : '' }}">
								<i class="far fa-circle nav-icon"></i>
								<p>Anti Money Laundering</p>
							</a>
						</li>

                        <li class="nav-item">
							<a href="{{route('privacyPolicy.create')}}" class="nav-link {{ ( Route::currentRouteName() == 'privacyPolicy.create' ) ? 'active' : '' }}" >
								<i class="far fa-circle nav-icon"></i>
								<p>Privacy Policy</p>
							</a>
						</li>

                        <li class="nav-item">
							<a href="{{route('termsAndServices.create')}}" class="nav-link {{ ( Route::currentRouteName() == 'termsAndServices.create' ) ? 'active' : '' }}">
								<i class="far fa-circle nav-icon"></i>
								<p>Terms of Service</p>
							</a>
						</li>

                        

                        <li class="nav-item">
							<a href="{{route('contactUs.index')}}" class="nav-link {{ ( Route::currentRouteName() == 'contactUs.index' ) ? 'active' : '' }}">
								<i class="far fa-circle nav-icon"></i>
								<p>Contact Us</p>
							</a>
						</li>
						
					</ul>
				</li>
                 {{-- <li class="nav-item">
                     <a href="#" class="nav-link">
                         <i class="nav-icon fas fa-chart-pie"></i>
                         <p>
                             Charts
                             <i class="right fas fa-angle-left"></i>
                         </p>
                     </a>
                     <ul class="nav nav-treeview">
                         <li class="nav-item">
                             <a href="pages/charts/chartjs.html" class="nav-link">
                                 <i class="far fa-circle nav-icon"></i>
                                 <p>ChartJS</p>
                             </a>
                         </li>
                         <li class="nav-item">
                             <a href="pages/charts/flot.html" class="nav-link">
                                 <i class="far fa-circle nav-icon"></i>
                                 <p>Flot</p>
                             </a>
                         </li>
                         <li class="nav-item">
                             <a href="pages/charts/inline.html" class="nav-link">
                                 <i class="far fa-circle nav-icon"></i>
                                 <p>Inline</p>
                             </a>
                         </li>
                         <li class="nav-item">
                             <a href="pages/charts/uplot.html" class="nav-link">
                                 <i class="far fa-circle nav-icon"></i>
                                 <p>uPlot</p>
                             </a>
                         </li>
                     </ul>
                 </li>
                 <li class="nav-item">
                     <a href="#" class="nav-link">
                         <i class="nav-icon fas fa-tree"></i>
                         <p>
                             UI Elements
                             <i class="fas fa-angle-left right"></i>
                         </p>
                     </a>
                     <ul class="nav nav-treeview">
                         <li class="nav-item">
                             <a href="pages/UI/general.html" class="nav-link">
                                 <i class="far fa-circle nav-icon"></i>
                                 <p>General</p>
                             </a>
                         </li>
                         <li class="nav-item">
                             <a href="pages/UI/icons.html" class="nav-link">
                                 <i class="far fa-circle nav-icon"></i>
                                 <p>Icons</p>
                             </a>
                         </li>
                     </ul>
                 </li> --}}
             </ul>
         </nav>
         <!-- /.sidebar-menu -->
     </div>
     <!-- /.sidebar -->
 </aside>

 @push('custom-script')
    <script>
         $(document).ready(function () {
            
            var name = '<?= Auth::user()->name ?>';
            var intials = name.charAt(0).toUpperCase(); 
            
            var profileImage = $('#profileImage').text(intials);

        })
    </script>
 @endpush

resources/views/admin/partials/script.blade.php
<!-- jQuery -->
<script src="{{asset('backend/plugins/jquery/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('backend/plugins/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{asset('backend/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
{{-- <!-- ChartJS -->
<script src="{{asset('backend/plugins/chart.js/Chart.min.js')}}"></script>
<!-- Sparkline -->
<script src="{{asset('backend/plugins/sparklines/sparkline.js')}}"></script>
<!-- JQVMap -->
<script src="{{asset('backend/plugins/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{asset('backend/plugins/jqvmap/maps/jquery.vmap.usa.js')}}"></script> --}}
<!-- jQuery Knob Chart -->
<script src="{{asset('backend/plugins/jquery-knob/jquery.knob.min.js')}}"></script>
<!-- daterangepicker -->
<script src="{{asset('backend/plugins/moment/moment.min.js')}}"></script>
<script src="{{asset('backend/plugins/daterangepicker/daterangepicker.js')}}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{asset('backend/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<!-- Summernote -->
<script src="{{asset('backend/plugins/summernote/summernote-bs4.min.js')}}"></script>
<!-- overlayScrollbars -->
<script src="{{asset('backend/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('backend/dist/js/adminlte.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('backend/dist/js/demo.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{{-- <script src="{{asset('backend/dist/js/pages/dashboard.js')}}"></script> --}}
@stack('custom-script')

resources/views/admin/partials/style.blade.php
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('backend/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{{asset('backend/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{{asset('backend/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
  <!-- JQVMap -->
  {{-- <link rel="stylesheet" href="{{asset('backend/plugins/jqvmap/jqvmap.min.css')}}"> --}}
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('backend/dist/css/adminlte.min.css')}}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{asset('backend/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{{asset('backend/plugins/daterangepicker/daterangepicker.css')}}">
  <!-- summernote -->
  <link rel="stylesheet" href="{{asset('backend/plugins/summernote/summernote-bs4.min.css')}}">
  @stack('custom-css')